IMPORTANDO LIBRERRIA NUMPHY

In [1]:
import numpy as np

Creando una lista de 10 Elementos

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Transformando la Lista a un Array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Corroborando el tipo de estructura

In [4]:
type(arreglo)

numpy.ndarray

Corroborando el tipo de datos del arreglo

In [5]:
arreglo.dtype

dtype('int32')

Definiendo el Array de int32 a float32

In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

Sigue siendo un array de int32

In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Transformando los datos de int32 a float32

In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

También existe una función similar a Range pero ocupando Arrays

In [9]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Arreglo de 2 en 2 utilizando Arange

In [10]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

ALGUNAS FUNCIONES DE NUMPY

Obteniendo el promedio del array

In [11]:
promedio = np.mean(arreglo)
promedio

5.5

Obteniendo la mediana del array

In [12]:
mediana = np.median(arreglo)
mediana

5.5

Desviación Estandar del Arreglo

In [13]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

Generación de un arreglo de 10 elementos de solo unos

In [14]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Generación de un arreglo de 10 elementos de solo ceros

In [15]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

Transformando el arreglo de unos de punto flotante a enteros

In [16]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

UTILIZANDO LA FUNCIÓN RANDOM

Generando arreglo aleatorio de 5 elementos

In [17]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.5960406 , 0.2652449 , 0.71818494, 0.69004743, 0.02451443,
       0.91227939, 0.8552483 , 0.29611745, 0.82160113, 0.8843375 ])

Generando una matriz aleatoria de 3x3

In [18]:
matriz = np.random.rand(3,3)
matriz

array([[0.92563094, 0.59522999, 0.81746903],
       [0.76505749, 0.04212701, 0.41794835],
       [0.87244215, 0.38547343, 0.07360064]])

Generando un arreglo aleatorio de 10 números enteros del 1 al 5

In [19]:
arreglo_aleatorio2  = np.random.randint(1,1001,5)
arreglo_aleatorio2

array([554, 593, 266, 542, 626])